var creepList=[
    {
        'Name':'Collect',
        'Memory':'collect',
        'Action':[WORK,WORK,WORK,WORK,WORK,MOVE,CARRY]
    },
    {
        'Name':'Harvester',
        'Memory':'harvester',
        'Action':[WORK,MOVE,MOVE,CARRY,CARRY,CARRY]
    }
    ,
    {
        'Name':'Builder',
        'Memory':'builder',
        'Action':[WORK,MOVE,MOVE,CARRY,CARRY,CARRY]
    }
    ,
    {
        'Name':'Upgrader',
        'Memory':'upgrader',
        'Action':[WORK,WORK,WORK,MOVE,MOVE,CARRY,CARRY,CARRY]
    }
];